projects:
  apolloGraphqlApi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: qdxbk7vqpjh7dhxlmt2lu4ehf4
      endpoints:
        prod: >-
          https://udztsnggkvhadl4rhaj2fdyaqa.appsync-api.us-east-1.amazonaws.com/graphql
